<?php

return [
    'definitions' => [
        ['name' => 'dashboard.view', 'group' => 'dashboard', 'label' => 'View dashboard'],
        ['name' => 'machines.view', 'group' => 'machines', 'label' => 'View machines'],
        ['name' => 'machines.create', 'group' => 'machines', 'label' => 'Create machines'],
        ['name' => 'machines.update', 'group' => 'machines', 'label' => 'Update machines'],
        ['name' => 'machines.delete', 'group' => 'machines', 'label' => 'Delete machines'],
        ['name' => 'workorders.view', 'group' => 'workorders', 'label' => 'View work orders'],
        ['name' => 'workorders.create', 'group' => 'workorders', 'label' => 'Create work orders'],
        ['name' => 'workorders.update', 'group' => 'workorders', 'label' => 'Update work orders'],
        ['name' => 'workorders.delete', 'group' => 'workorders', 'label' => 'Delete work orders'],
        ['name' => 'workorders.update_status', 'group' => 'workorders', 'label' => 'Update work order status'],
        ['name' => 'workorders.update_notes', 'group' => 'workorders', 'label' => 'Update work order notes'],
        ['name' => 'workorders.verify_close', 'group' => 'workorders', 'label' => 'Verify and close work orders'],
        ['name' => 'workorders.cancel', 'group' => 'workorders', 'label' => 'Cancel work orders'],
        ['name' => 'faults.view', 'group' => 'faults', 'label' => 'View fault reports'],
        ['name' => 'faults.report', 'group' => 'faults', 'label' => 'Report faults'],
        ['name' => 'faults.convert', 'group' => 'faults', 'label' => 'Convert faults to work orders'],
        ['name' => 'faults.dismiss', 'group' => 'faults', 'label' => 'Dismiss fault reports'],
        ['name' => 'repairs.view', 'group' => 'repairs', 'label' => 'View repair records'],
        ['name' => 'repairs.create', 'group' => 'repairs', 'label' => 'Create repair records'],
        ['name' => 'repairs.update', 'group' => 'repairs', 'label' => 'Update repair records'],
        ['name' => 'repairs.delete', 'group' => 'repairs', 'label' => 'Delete repair records'],
        ['name' => 'analytics.view', 'group' => 'analytics', 'label' => 'View analytics'],
        ['name' => 'finance.view', 'group' => 'finance', 'label' => 'View finance'],
        ['name' => 'finance.edit', 'group' => 'finance', 'label' => 'Edit finance entries'],
        ['name' => 'notifications.view', 'group' => 'notifications', 'label' => 'View notifications'],
        ['name' => 'notifications.manage', 'group' => 'notifications', 'label' => 'Manage notifications'],
        ['name' => 'users.view', 'group' => 'users', 'label' => 'View users'],
        ['name' => 'users.create', 'group' => 'users', 'label' => 'Create users'],
        ['name' => 'users.update', 'group' => 'users', 'label' => 'Update users'],
        ['name' => 'users.delete', 'group' => 'users', 'label' => 'Delete users'],
        ['name' => 'technicians.manage', 'group' => 'technicians', 'label' => 'Manage technicians'],
        ['name' => 'roles.view', 'group' => 'roles', 'label' => 'View roles'],
        ['name' => 'roles.create', 'group' => 'roles', 'label' => 'Create roles'],
        ['name' => 'roles.update', 'group' => 'roles', 'label' => 'Update roles'],
        ['name' => 'roles.delete', 'group' => 'roles', 'label' => 'Delete roles'],
    ],

    'roles' => [
        'Super Admin' => ['*'],
        'Owner' => [
            'dashboard.view',
            'machines.view', 'machines.create', 'machines.update', 'machines.delete',
            'workorders.view', 'workorders.create', 'workorders.update', 'workorders.delete',
            'workorders.update_status', 'workorders.update_notes', 'workorders.verify_close', 'workorders.cancel',
            'faults.view', 'faults.report', 'faults.convert', 'faults.dismiss',
            'repairs.view', 'repairs.create', 'repairs.update', 'repairs.delete',
            'analytics.view', 'finance.view', 'finance.edit', 'notifications.view', 'notifications.manage',
            'users.view', 'users.create', 'users.update', 'users.delete', 'technicians.manage',
            'roles.view', 'roles.create', 'roles.update', 'roles.delete',
        ],
        'Manager' => [
            'dashboard.view',
            'machines.view', 'machines.create', 'machines.update', 'machines.delete',
            'workorders.view', 'workorders.create', 'workorders.update', 'workorders.delete',
            'workorders.update_status', 'workorders.update_notes', 'workorders.verify_close', 'workorders.cancel',
            'faults.view', 'faults.report', 'faults.convert', 'faults.dismiss',
            'repairs.view', 'repairs.create', 'repairs.update', 'repairs.delete',
            'analytics.view', 'finance.view', 'finance.edit', 'notifications.view', 'notifications.manage',
            'users.view', 'users.create', 'users.update', 'users.delete', 'technicians.manage',
            'roles.view', 'roles.create', 'roles.update', 'roles.delete',
        ],
        'Technician' => [
            'dashboard.view', 'machines.view', 'workorders.view',
            'workorders.update_status', 'workorders.update_notes', 'workorders.cancel',
            'faults.view', 'faults.report', 'repairs.view', 'notifications.view',
        ],
        'Worker' => [
            'dashboard.view', 'machines.view', 'workorders.view',
            'faults.view', 'faults.report', 'repairs.view', 'notifications.view',
        ],
        'Finance' => [
            'dashboard.view', 'machines.view', 'workorders.view', 'faults.view', 'repairs.view',
            'analytics.view', 'finance.view', 'finance.edit', 'notifications.view',
        ],
    ],
];
